//! Vendored Agent execution trace types.
//!
//! vendored from 2b-svc-kova/kova-types/src/trace.rs (v0.2.0), keep in sync
//! (last synced 2026-06-01: added `AgentTrace::schema_version`)
//!
//! Lumen consumes Kova's `AgentTrace`/`TraceStep`/`TraceStepType`/`TraceStatus`
//! (and their `TokenUsage` dependency) purely as data read back from trace JSON
//! files. To keep this open-core mirror buildable from a single `git clone`
//! (no private sibling repo / unpublished crate), these types are vendored here
//! instead of pulled via a path/version dependency on `kova-types`.
//!
//! Only the trace surface lumen-core reads is vendored. `TokenUsage` is the
//! sole transitive dependency (originally `kova_types::llm::TokenUsage`); the
//! rest of `kova-types::llm` is intentionally NOT vendored.

use core::fmt;

use serde::{Deserialize, Serialize};

/// Token usage statistics from an LLM response.
///
/// vendored from 2b-svc-kova/kova-types/src/llm.rs (v0.2.0), keep in sync
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct TokenUsage {
    /// Number of tokens in the prompt.
    pub prompt_tokens: u32,
    /// Number of tokens generated by the model.
    pub completion_tokens: u32,
}

impl TokenUsage {
    /// Total tokens (prompt + completion).
    #[must_use]
    pub const fn total(self) -> u32 {
        self.prompt_tokens.saturating_add(self.completion_tokens)
    }

    /// Accumulate another usage into this one.
    pub fn accumulate(&mut self, other: Self) {
        self.prompt_tokens = self.prompt_tokens.saturating_add(other.prompt_tokens);
        self.completion_tokens = self
            .completion_tokens
            .saturating_add(other.completion_tokens);
    }
}

impl fmt::Display for TokenUsage {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{}+{}={}",
            self.prompt_tokens,
            self.completion_tokens,
            self.total()
        )
    }
}

/// Complete trace of a single Agent execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentTrace {
    /// Unique trace identifier.
    pub trace_id: String,
    /// Agent that produced this trace.
    pub agent_id: String,
    /// Associated task ID (0 for standalone agent runs).
    pub task_id: u64,
    /// Ordered list of execution steps.
    pub steps: Vec<TraceStep>,
    /// Current trace status.
    pub status: TraceStatus,
    /// Cumulative token usage across all LLM calls.
    pub total_tokens: TokenUsage,
    /// Estimated total cost in USD.
    pub total_cost_usd: f64,
    /// Unix epoch milliseconds when the trace started.
    pub started_at_ms: u64,
    /// Unix epoch milliseconds when the trace completed (None if still running).
    pub completed_at_ms: Option<u64>,
    /// Trace id of the run this trace resumed from after a crash, if any.
    ///
    /// `None` for a fresh run. Set on a crash-recovered run so consumers can
    /// link "Run B resumed from Run A" into one story instead of showing two
    /// unrelated traces. `#[serde(default)]` keeps pre-existing trace JSON
    /// (written before this field existed) readable.
    #[serde(default)]
    pub parent_trace_id: Option<String>,
    /// On-disk trace schema version, stamped by Kova's constructors
    /// (`TRACE_SCHEMA_VERSION` = 1 at the time of this sync).
    ///
    /// `#[serde(default)]` yields `0` for legacy trace JSON written before this
    /// field existed, letting consumers tell a current trace (`1`) apart from a
    /// pre-versioning one (`0`) without breaking the read path.
    #[serde(default)]
    pub schema_version: u32,
}

/// A single step within an Agent execution trace.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TraceStep {
    /// Step number (0-indexed).
    pub step_num: u32,
    /// Type and details of this step.
    pub step_type: TraceStepType,
    /// Unix epoch milliseconds when this step started.
    pub started_at_ms: u64,
    /// Duration of this step in milliseconds.
    pub duration_ms: u64,
    /// Token usage for this step (only for LLM calls).
    pub tokens: Option<TokenUsage>,
    /// Arbitrary key-value metadata.
    pub metadata: Vec<(String, String)>,
}

/// Classification of a trace step.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TraceStepType {
    /// LLM completion call.
    LlmCall {
        /// Model identifier used.
        model: String,
        /// Why the model stopped generating.
        finish_reason: String,
    },
    /// Tool execution.
    ToolCall {
        /// Name of the tool invoked.
        tool_name: String,
        /// Whether the tool succeeded.
        success: bool,
    },
    /// WAL checkpoint written.
    Checkpoint {
        /// Iteration number at checkpoint.
        iteration: u32,
    },
    /// Error occurred during execution.
    Error {
        /// Error description.
        message: String,
    },
}

/// Status of an Agent trace.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum TraceStatus {
    /// Agent is still executing.
    Running,
    /// Agent completed successfully.
    Completed,
    /// Agent failed with an error.
    Failed(String),
}

impl fmt::Display for TraceStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Running => f.write_str("running"),
            Self::Completed => f.write_str("completed"),
            Self::Failed(msg) => write!(f, "failed: {msg}"),
        }
    }
}

impl fmt::Display for TraceStepType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::LlmCall { model, .. } => write!(f, "llm_call({model})"),
            Self::ToolCall { tool_name, .. } => write!(f, "tool_call({tool_name})"),
            Self::Checkpoint { iteration } => write!(f, "checkpoint({iteration})"),
            Self::Error { message } => write!(f, "error({message})"),
        }
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    #[test]
    fn token_usage_total_and_accumulate() {
        let mut usage = TokenUsage {
            prompt_tokens: 100,
            completion_tokens: 50,
        };
        assert_eq!(usage.total(), 150);
        assert_eq!(usage.to_string(), "100+50=150");

        usage.accumulate(TokenUsage {
            prompt_tokens: 200,
            completion_tokens: 30,
        });
        assert_eq!(usage.prompt_tokens, 300);
        assert_eq!(usage.completion_tokens, 80);
        assert_eq!(usage.total(), 380);
    }

    #[test]
    fn token_usage_total_saturating() {
        let usage = TokenUsage {
            prompt_tokens: u32::MAX,
            completion_tokens: 1,
        };
        assert_eq!(usage.total(), u32::MAX);
    }

    #[test]
    fn token_usage_default_is_zero() {
        let usage = TokenUsage::default();
        assert_eq!(usage.prompt_tokens, 0);
        assert_eq!(usage.completion_tokens, 0);
        assert_eq!(usage.total(), 0);
    }

    #[test]
    fn trace_status_display() {
        assert_eq!(TraceStatus::Running.to_string(), "running");
        assert_eq!(TraceStatus::Completed.to_string(), "completed");
        assert_eq!(
            TraceStatus::Failed("oops".into()).to_string(),
            "failed: oops"
        );
    }

    #[test]
    fn trace_step_type_display() {
        assert_eq!(
            TraceStepType::LlmCall {
                model: "gpt-4o".into(),
                finish_reason: "stop".into()
            }
            .to_string(),
            "llm_call(gpt-4o)"
        );
        assert_eq!(
            TraceStepType::ToolCall {
                tool_name: "echo".into(),
                success: true
            }
            .to_string(),
            "tool_call(echo)"
        );
        assert_eq!(
            TraceStepType::Checkpoint { iteration: 3 }.to_string(),
            "checkpoint(3)"
        );
        assert_eq!(
            TraceStepType::Error {
                message: "fail".into()
            }
            .to_string(),
            "error(fail)"
        );
    }

    #[test]
    fn agent_trace_serde_roundtrip() {
        let json = r#"{
            "trace_id": "t-1",
            "agent_id": "agent-1",
            "task_id": 0,
            "steps": [
                {
                    "step_num": 0,
                    "step_type": {"LlmCall": {"model": "gpt-4o", "finish_reason": "stop"}},
                    "started_at_ms": 1000,
                    "duration_ms": 250,
                    "tokens": {"prompt_tokens": 100, "completion_tokens": 50},
                    "metadata": []
                }
            ],
            "status": "Completed",
            "total_tokens": {"prompt_tokens": 100, "completion_tokens": 50},
            "total_cost_usd": 0.0,
            "started_at_ms": 1000,
            "completed_at_ms": 1250
        }"#;
        let trace: AgentTrace = serde_json::from_str(json).unwrap();
        assert_eq!(trace.trace_id, "t-1");
        assert_eq!(trace.steps.len(), 1);
        assert_eq!(trace.status, TraceStatus::Completed);
        assert_eq!(trace.total_tokens.total(), 150);
        assert_eq!(trace.completed_at_ms, Some(1250));
    }
}
